[package]
name = "networking_challenges"
version = "1.0.2"
authors = ["ND Tai <49815011+ndtai772@users.noreply.github.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
